# Generated by Django 3.2.4 on 2021-06-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slotAvailabilityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slot_Availability_Event', models.DateTimeField(auto_now_add=True)),
                ('Event_id', models.IntegerField(null=True)),
                ('Slot_Availability_Timestamp', models.DateTimeField()),
                ('Distric_id', models.IntegerField()),
                ('Center_Name', models.CharField(max_length=30)),
                ('Center_Pincode', models.IntegerField()),
                ('Dose1_Quantity', models.IntegerField()),
                ('Dose2_Quantity', models.IntegerField()),
                ('Vaccine_Name', models.CharField(max_length=20)),
            ],
        ),
    ]
