# Generated by Django 3.2.4 on 2021-06-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotAvailabilityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField()),
                ('district_id', models.IntegerField()),
                ('center_name', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('available_capacity_dose1', models.IntegerField()),
                ('available_capacity_dose2', models.IntegerField()),
                ('vaccine', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='slotAvailabilityInfo',
        ),
    ]
