# Generated by Django 3.2.4 on 2021-06-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0002_auto_20210612_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotavailabilityevent',
            name='event_id',
        ),
        migrations.AlterField(
            model_name='slotavailabilityevent',
            name='id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
