# Generated by Django 3.2.4 on 2021-06-12 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0003_auto_20210612_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotavailabilityevent',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
