# Generated by Django 3.2.4 on 2021-06-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0005_alter_slotavailabilityevent_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotavailabilityevent',
            name='state_id',
            field=models.IntegerField(default=0),
        ),
    ]
