# Generated by Django 3.2.4 on 2021-06-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0006_slotavailabilityevent_state_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotavailabilityevent',
            name='event_details_json',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
