# Generated by Django 3.2.4 on 2021-06-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0007_slotavailabilityevent_event_details_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotavailabilityevent',
            name='available_capacity_dose1',
        ),
        migrations.RemoveField(
            model_name='slotavailabilityevent',
            name='available_capacity_dose2',
        ),
        migrations.RemoveField(
            model_name='slotavailabilityevent',
            name='vaccine',
        ),
    ]
