# Generated by Django 3.2.4 on 2021-06-18 16:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0008_auto_20210618_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotavailabilityevent',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False),
        ),
    ]
