# Generated by Django 3.2.4 on 2021-06-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0009_alter_slotavailabilityevent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotavailabilityevent',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
