# Generated by Django 3.2.4 on 2021-06-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0010_alter_slotavailabilityevent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotavailabilityevent',
            name='event_details_json',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
