# Generated by Django 3.2.4 on 2021-06-22 05:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0011_alter_slotavailabilityevent_event_details_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotavailabilityevent',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='slotavailabilityevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
