# Generated by Django 3.2.4 on 2021-06-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0012_auto_20210622_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotavailabilityevent',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='slotavailabilityevent',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
