# Generated by Django 3.2.4 on 2021-06-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0013_auto_20210625_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBMP_DIST_MESSAGES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_message', models.CharField(max_length=500)),
            ],
        ),
    ]
