# Generated by Django 3.2.4 on 2021-06-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0014_bbmp_dist_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbmp_dist_messages',
            name='event_message',
            field=models.CharField(max_length=10000),
        ),
    ]
