# Generated by Django 3.2.4 on 2021-06-29 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0015_alter_bbmp_dist_messages_event_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbmp_dist_messages',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 10, 3, 12, 64513, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
