# Generated by Django 3.2.4 on 2021-06-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0016_bbmp_dist_messages_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_message', models.CharField(max_length=10000)),
                ('timestamp', models.DateTimeField()),
                ('district_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='BBMP_DIST_MESSAGES',
        ),
    ]
