# Generated by Django 3.2.4 on 2021-06-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0017_auto_20210630_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmessages',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
