# Generated by Django 3.2.4 on 2021-06-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0018_alter_rawmessages_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotavailabilityevent',
            name='center_name',
            field=models.CharField(max_length=100),
        ),
    ]
