# Generated by Django 3.2.4 on 2021-06-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0019_alter_slotavailabilityevent_center_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmessages',
            name='district_id',
            field=models.IntegerField(),
        ),
    ]
