# Generated by Django 3.2.4 on 2021-06-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0020_alter_rawmessages_district_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmessages',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
