# Generated by Django 3.2.4 on 2021-06-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0021_alter_rawmessages_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotavailabilityevent',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
