# Generated by Django 3.2.4 on 2021-07-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0023_predictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictions',
            name='status',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='predictions',
            name='id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
