# Generated by Django 3.2.4 on 2021-07-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0025_alter_predictions_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictions',
            name='center_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='predictions',
            name='district_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='predictions',
            name='pincode',
            field=models.IntegerField(blank=True),
        ),
    ]
