# Generated by Django 3.2.4 on 2021-07-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotTrackerApp', '0026_auto_20210706_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictions',
            name='center_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='predictions',
            name='district_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictions',
            name='forecast_json',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='predictions',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictions',
            name='time_statistics_json',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
